### ISSUE TITLE
InventoryGUI Player Inventory

### ISSUE THREAD

**Issue by AtSignRANK** [ProjectTL12345/InventoryGUI#9]
InventoryGUI 에서 **slot(i, stack) {}** 형식으로 작성했을때, 그것이 InventoryGUI 에서만이 아니라 Player Inventory 의 i 번째 칸을 클릭해도 일어남.
![image](https://user-images.githubusercontent.com/81941006/134456761-c3cfc66b-a599-4542-aa66-fb7301d7a719.png)
를 클릭했을때와
![image](https://user-images.githubusercontent.com/81941006/134456750-e3193f0a-3307-4ee2-8bf1-5cd9126ce176.png)
를 클릭 했을때, 똑같이 적용됨.

**Comment by ProjectTL12345** [comment]
fixed!
